apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testkr
  name: testkr
spec:
  replicas: 5
  selector:
    matchLabels:
      app: testkr
  template:
    metadata:
      labels:
        app: testkr
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpdd
  strategy:
    type: Recreate
