apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kreker
  name: kreker
spec:
  containers:
  - image: nginx
    name: kreker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
